export interface TranscriptSegment {
    text: string;
    duration: number;
    offset: number;
}

export interface ProcessedTranscript {
    structuredTranscript: string;
    summary: string;
}

export interface TranscriptOptions {
    language?: string;
    autoGenerated?: boolean;
} 