export interface TranscriptSegment {
    text: string;
    duration: number;
    offset: number;
}

export interface ProcessedTranscript {
    videoInfo: VideoInfo;
    structuredTranscript: string;
    summary: string;
}

export interface VideoInfo {
    videoId: string;
    title: string;
    channelName: string;
    publishedAt: string;
    thumbnailUrl: string;
}

export interface TranscriptOptions {
    language?: string;
    autoGenerated?: boolean;
}

export interface RapidAPIResponse {
    title: string;
    description: string;
    duration: string;
    thumbnail: string;
    like_count: number;
    channel: string;
    channel_url: string;
    text: string;
    transcript: {
        text: string;
        start: number;
        end: number;
    }[];
} 