export interface TranscriptSegment {
    text: string;
    duration: number;
    offset: number;
}

export interface VideoInfo {
    videoId: string;
    title: string;
    channelName: string;
    thumbnailUrl: string;
    publishedAt: string;
}

export interface ProcessingResult {
    videoInfo: VideoInfo;
    structuredTranscript: string;
    summary: string;
}

export interface ProcessingUpdate {
    progress: number;
    step: string;
    error?: string;
    done?: boolean;
    videoInfo?: VideoInfo;
    structuredTranscript?: string;
    summary?: string;
}

export interface TranscriptOptions {
    language?: string;
    autoGenerated?: boolean;
} 